#测试环境
spring:
    datasource:
         druid: time-between-eviction-runs-millis:60000
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://localhost:3306/vip_file_manager?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
         username: root
         password: 1qaz@WSX
         driver-class-name: com.mysql.cj.jdbc.Driver
         #配置druid监控统计拦截的filters
         filters: stat
    config:
      activate:
        on-profile: dev
file:
  # 文件存储路径
  save-path: D:/temp/file-manager
  # 断点续传文件配置路径
  conf-path: D:/temp/file-manager/conf
  # 合成视频存放路径
  compose-path: D:/temp/video/
  #  合成视频播放地址
  request-path: /video/
#  server-path: http://192.168.1.254:9000/videoFile/
  # 磁盘大小
  directory-path: D:/
  # 视频存储路径
  save-file-path: D:/temp
ffmpeg:
  folderPath: /home/user/wuxibank/java/ffmpeg.exe
  resourcePath: ffmpeg/ffmpeg.exe
compose:
  compose_time: 2
  compose_rules: minute