server:
  port: 9555
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
 #多环境配置
  profiles:
    active: test
  servlet:
  #上传文件大小
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
  # 关闭mybatisplus启动图标
    banner: off
    db-config:
      # 全局默认主键类型
      id-type: AUTO
      # 表名、是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  mapper-locations:
  - /mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: count=countsql
swagger:
  title: VIP-FILE-MANAGER Swagger API
  description: 本地文件管理服务
  version: 1.0.0
logging:
  config: classpath:logback.xml
upload:
  path: /data/project/wuxibank/temp/file-manager
authentication_api:
  appKey: Video001
  appSecret: videorenzhen
  token: /RZIMS-api/video/v1/getAppToken
  set-video-file: /RZIMS-api/video/v1/setVideoFile