##生产环境
spring:
    datasource:
         druid: time-between-eviction-runs-millis:60000
         type: com.alibaba.druid.pool.DruidDataSource
         #192.168.13.27
         url: jdbc:mysql://localhost:3306/vip_file_manager?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
         username: root
         password: User1qw2!QW@
         driver-class-name: com.mysql.cj.jdbc.Driver
         #配置druid监控统计拦截的filters
         filters: stat
    config:
      activate:
        on-profile: prod
file:
  # 文件存储路径
  save-path: /data/project/wuxibank/temp/file-manager
  # 断点续传文件配置路径
  conf-path: /data/project/wuxibank/wuxibank/temp/file-manager/conf
  # 合成视频存放路径
  compose-path: /data/project/wuxibank/temp/files/
  #  合成视频播放地址
  request-path: /video/
  server-path: http://192.168.13.27:8080/videoFile/
compose:
  compose_time: 2
  compose_rules: minute
ffmpeg:
  folderPath: /home/user/bankbranch/java/ffmpeg
  resourcePath: ffmpeg/ffmpeg